name: workflow-input-demop
on:
  workflow_dispatch:
    branches:
      - 'release/**'
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        options:
        - dev
        - uat
        - prod
        - prod-ca
        required: true
   

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - name: print msg
      run: echo "${{ github.event.inputs.message }}- ${{ github.event.inputs.environment }}"
